# Add funding handles when the project is ready to accept sponsorship.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [JacobFV]
# open_collective: yt2ctx
# thanks_dev: u/gh/JacobFV
