"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { FormEvent } from "react";

import { STAGE_PLAN } from "../core/progress";
import type { ProgressEvent } from "../core/types";
import type {
  AnalyzeResult,
  BillingSummary,
  Frame,
  SavedVideoSummary,
  SlopWarning,
  User
} from "./result-types";
import { SiteFooter, SiteHeader } from "./site-chrome";

type Phase = "compose" | "running" | "done";
type ResultTab = "watch" | "frames" | "style" | "shot-specs" | "prompt" | "warnings";

/* ------------------------------------------------------------------ *
 * Pure helpers                                                        *
 * ------------------------------------------------------------------ */

const ID_PATTERN = /^[\w-]{11}$/;

function parseYouTubeId(input: string): string | null {
  const trimmed = input.trim();
  if (!trimmed) return null;
  if (ID_PATTERN.test(trimmed)) return trimmed;
  let parsed: URL;
  try {
    parsed = new URL(trimmed.includes("://") ? trimmed : `https://${trimmed}`);
  } catch {
    return null;
  }
  const host = parsed.hostname.replace(/^www\./, "");
  if (host === "youtu.be") {
    const id = parsed.pathname.slice(1).split("/")[0];
    return ID_PATTERN.test(id) ? id : null;
  }
  if (host.endsWith("youtube.com") || host.endsWith("youtube-nocookie.com")) {
    const v = parsed.searchParams.get("v");
    if (v && ID_PATTERN.test(v)) return v;
    const match = parsed.pathname.match(/\/(?:shorts|embed|live|v)\/([\w-]{11})/);
    if (match) return match[1];
  }
  return null;
}

function thumbnailUrl(id: string): string {
  return `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
}

function formatTimestamp(seconds: number): string {
  const safe = Math.max(0, Math.floor(seconds || 0));
  const hours = Math.floor(safe / 3600);
  const minutes = Math.floor((safe % 3600) / 60);
  const rest = safe % 60;
  const core = `${String(minutes).padStart(2, "0")}:${String(rest).padStart(2, "0")}`;
  return hours > 0 ? `${hours}:${core}` : core;
}

function formatClock(ms: number): string {
  const total = Math.max(0, Math.round(ms / 1000));
  const minutes = Math.floor(total / 60);
  const seconds = total % 60;
  return `${minutes}:${String(seconds).padStart(2, "0")}`;
}

function downloadBlob(href: string, fileName: string) {
  const anchor = document.createElement("a");
  anchor.href = href;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
}

function downloadText(text: string, fileName: string) {
  const blob = new Blob([text], { type: "text/markdown;charset=utf-8" });
  const href = URL.createObjectURL(blob);
  downloadBlob(href, fileName);
  setTimeout(() => URL.revokeObjectURL(href), 1000);
}

/* Minimal, escape-first Markdown renderer for the document tabs. The input is
 * machine-generated by this project, so a small grammar covers it safely. */
function escapeHtml(value: string): string {
  return value.replace(/[&<>"]/g, (char) => {
    if (char === "&") return "&amp;";
    if (char === "<") return "&lt;";
    if (char === ">") return "&gt;";
    return "&quot;";
  });
}

function renderInline(value: string): string {
  return escapeHtml(value)
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
}

function markdownToHtml(markdown: string): string {
  const out: string[] = [];
  let listOpen = false;
  const closeList = () => {
    if (listOpen) {
      out.push("</ul>");
      listOpen = false;
    }
  };
  for (const line of markdown.split("\n")) {
    if (!line.trim()) {
      closeList();
      continue;
    }
    const heading = line.match(/^(#{1,6})\s+(.*)$/);
    if (heading) {
      closeList();
      const level = heading[1].length;
      out.push(`<h${level}>${renderInline(heading[2])}</h${level}>`);
      continue;
    }
    if (/^---+\s*$/.test(line)) {
      closeList();
      out.push("<hr/>");
      continue;
    }
    const bullet = line.match(/^\s*[-*]\s+(.*)$/);
    if (bullet) {
      if (!listOpen) {
        out.push("<ul>");
        listOpen = true;
      }
      out.push(`<li>${renderInline(bullet[1])}</li>`);
      continue;
    }
    closeList();
    out.push(`<p>${renderInline(line)}</p>`);
  }
  closeList();
  return out.join("\n");
}

function warningsToText(warnings: SlopWarning[]): string {
  return warnings
    .map(
      (warning) =>
        `${warning.rule}\nWhy: ${warning.whyItBreaksTaste}\nReject if: ${warning.rejectIf}\nPrefer: ${warning.preferredMove}`
    )
    .join("\n\n");
}

/* ------------------------------------------------------------------ *
 * Component                                                           *
 * ------------------------------------------------------------------ */

const TAB_LABELS: Record<ResultTab, string> = {
  watch: "Watch Pack",
  frames: "Frames",
  style: "Style Bible",
  "shot-specs": "Shot Specs",
  prompt: "Codex Prompt",
  warnings: "Slop Warnings"
};

const TAB_FILES: Partial<Record<ResultTab, string>> = {
  watch: "watch.md",
  style: "style-bible.md",
  "shot-specs": "shot-specs.md",
  prompt: "codex-prompt.md"
};

export default function Home() {
  // Auth state
  const [user, setUser] = useState<User | null>(null);
  const [billing, setBilling] = useState<BillingSummary | null>(null);
  const [authLoading, setAuthLoading] = useState(true);

  // Form state
  const [url, setUrl] = useState("");
  const [topK, setTopK] = useState(8);
  const [mode, setMode] = useState<"density" | "top-k">("density");
  const [extractionKind, setExtractionKind] = useState<"text" | "full">("text");
  const [candidateIntervalSeconds, setCandidateIntervalSeconds] = useState(8);
  const [maxCandidateFrames, setMaxCandidateFrames] = useState(36);
  const [tuningOpen, setTuningOpen] = useState(false);

  // Run state
  const [phase, setPhase] = useState<Phase>("compose");
  const [progress, setProgress] = useState<ProgressEvent | null>(null);
  const [discoveredTitle, setDiscoveredTitle] = useState<string | null>(null);
  const [elapsedMs, setElapsedMs] = useState(0);
  const [error, setError] = useState("");

  // Result state
  const [result, setResult] = useState<AnalyzeResult | null>(null);
  const [activeTab, setActiveTab] = useState<ResultTab>("style");
  const [viewRaw, setViewRaw] = useState(false);
  const [lightbox, setLightbox] = useState<number | null>(null);
  const [toast, setToast] = useState("");

  // Saved videos — past analyses kept in Postgres for the signed-in user.
  const [saved, setSaved] = useState<SavedVideoSummary[]>([]);
  const [savedLoading, setSavedLoading] = useState(false);

  const abortRef = useRef<AbortController | null>(null);
  const runStartRef = useRef(0);

  const videoId = useMemo(() => parseYouTubeId(url), [url]);
  const canSubmit = url.trim().length > 0 && phase !== "running";

  /* Hydrate the signed-in account and its saved video list. */
  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const response = await fetch("/api/me", { cache: "no-store" });
        const payload = (await response.json()) as { user: User | null; billing: BillingSummary };
        if (!alive) return;
        setUser(payload.user);
        setBilling(payload.billing);
        setExtractionKind(payload.user ? "full" : "text");
        if (payload.user) await refreshVideos();
      } finally {
        if (alive) setAuthLoading(false);
      }
    })();
    return () => {
      alive = false;
    };
  }, []);

  /* Live elapsed clock while a run is in flight. */
  useEffect(() => {
    if (phase !== "running") return;
    const tick = () => setElapsedMs(Date.now() - runStartRef.current);
    tick();
    const timer = window.setInterval(tick, 250);
    return () => window.clearInterval(timer);
  }, [phase]);

  /* Toast auto-dismiss. */
  useEffect(() => {
    if (!toast) return;
    const timer = window.setTimeout(() => setToast(""), 2200);
    return () => window.clearTimeout(timer);
  }, [toast]);

  /* Lightbox keyboard navigation. */
  useEffect(() => {
    if (lightbox === null || !result) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") setLightbox(null);
      if (event.key === "ArrowRight")
        setLightbox((index) => (index === null ? null : (index + 1) % result.frames.length));
      if (event.key === "ArrowLeft")
        setLightbox((index) =>
          index === null ? null : (index - 1 + result.frames.length) % result.frames.length
        );
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [lightbox, result]);

  const flashToast = useCallback((message: string) => setToast(message), []);

  async function refreshVideos() {
    setSavedLoading(true);
    try {
      const response = await fetch("/api/videos", { cache: "no-store" });
      if (response.status === 401) {
        setUser(null);
        setExtractionKind("text");
        setSaved([]);
        return;
      }
      const payload = (await response.json()) as { videos?: SavedVideoSummary[] };
      setSaved(payload.videos ?? []);
    } finally {
      setSavedLoading(false);
    }
  }

  function handleAuthenticated(nextUser: User) {
    setUser(nextUser);
    setExtractionKind("full");
    setPhase("compose");
    setResult(null);
    setError("");
    void refreshVideos();
  }

  async function logout() {
    await fetch("/api/auth/logout", { method: "POST" });
    abortRef.current?.abort();
    setUser(null);
    setBilling(null);
    setExtractionKind("text");
    setSaved([]);
    setResult(null);
    setPhase("compose");
    flashToast("Signed out");
  }

  async function submit() {
    if (!canSubmit) return;
    const controller = new AbortController();
    abortRef.current = controller;
    runStartRef.current = Date.now();

    setPhase("running");
    setError("");
    setResult(null);
    setDiscoveredTitle(null);
    setElapsedMs(0);
    setProgress({ stage: "info", label: "Reading metadata", pct: 0, elapsedMs: 0 });

    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/x-ndjson" },
        body: JSON.stringify({
          url,
          topK,
          mode,
          extractionKind,
          candidateIntervalSeconds,
          maxCandidateFrames,
          frameWidth: 768
        }),
        signal: controller.signal
      });

      if (!response.ok || !response.body) {
        const payload = await response.json().catch(() => ({}));
        throw new Error(payload.error || `Request failed (${response.status})`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      let finalResult: AnalyzeResult | null = null;

      const consume = (line: string) => {
        if (!line.trim()) return;
        const event = JSON.parse(line) as
          | ({ type: "progress" } & ProgressEvent)
          | { type: "result"; result: AnalyzeResult }
          | { type: "error"; message: string };
        if (event.type === "progress") {
          setProgress(event);
          if (event.stage === "download" && event.detail) setDiscoveredTitle(event.detail);
        } else if (event.type === "result") {
          finalResult = event.result;
        } else if (event.type === "error") {
          throw new Error(event.message);
        }
      };

      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";
        for (const line of lines) consume(line);
      }
      if (buffer.trim()) consume(buffer);

      if (!finalResult) throw new Error("The analysis stream ended without a result.");
      const completedResult = finalResult as AnalyzeResult;
      setResult(completedResult);
      setActiveTab(completedResult.extractionKind === "text" ? "watch" : "style");
      setViewRaw(false);
      setPhase("done");
      await refreshBilling();
      await refreshVideos();
    } catch (caught) {
      if (controller.signal.aborted) {
        setPhase("compose");
        return;
      }
      setError(caught instanceof Error ? caught.message : "Analysis failed");
      setPhase("compose");
    } finally {
      abortRef.current = null;
    }
  }

  function cancelRun() {
    abortRef.current?.abort();
    setPhase("compose");
  }

  function resetToCompose() {
    setPhase("compose");
    setResult(null);
    setProgress(null);
    setError("");
  }

  /* Re-open a saved video straight into its result view. */
  async function openSavedVideo(video: SavedVideoSummary) {
    abortRef.current?.abort();
    const response = await fetch(`/api/videos/${video.id}`, { cache: "no-store" });
    if (!response.ok) {
      flashToast(response.status === 404 ? "Video not found" : "Could not open video");
      if (response.status === 401) setUser(null);
      return;
    }
    const payload = (await response.json()) as { video: { result: AnalyzeResult; sourceUrl: string } };
    setUrl(payload.video.sourceUrl);
    setResult(payload.video.result);
    setActiveTab("style");
    setViewRaw(false);
    setLightbox(null);
    setError("");
    setProgress(null);
    setPhase("done");
    if (typeof window !== "undefined") window.scrollTo({ top: 0, behavior: "smooth" });
  }

  async function removeSavedVideo(id: string) {
    const response = await fetch(`/api/videos/${id}`, { method: "DELETE" });
    if (response.status === 401) {
      setUser(null);
      return;
    }
    setSaved((videos) => videos.filter((video) => video.id !== id));
    flashToast("Video deleted");
  }

  async function refreshBilling() {
    const response = await fetch("/api/me", { cache: "no-store" });
    const payload = (await response.json()) as { user: User | null; billing: BillingSummary };
    setUser(payload.user);
    setBilling(payload.billing);
  }

  async function startCheckout(action: "credits" | "recurring" | "setup", packId?: "starter" | "studio") {
    const response = await fetch("/api/billing/checkout", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action, packId })
    });
    const payload = (await response.json()) as { url?: string; error?: string };
    if (!response.ok || !payload.url) {
      flashToast(payload.error || "Billing could not start");
      return;
    }
    window.location.href = payload.url;
  }

  async function openBillingPortal() {
    const response = await fetch("/api/billing/portal", { method: "POST" });
    const payload = (await response.json()) as { url?: string; error?: string };
    if (!response.ok || !payload.url) {
      flashToast(payload.error || "Billing portal unavailable");
      return;
    }
    window.location.href = payload.url;
  }

  async function updateBillingSettings(settings: {
    autoRefillEnabled?: boolean;
    recurringEnabled?: boolean;
  }) {
    const response = await fetch("/api/billing/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(settings)
    });
    if (!response.ok) {
      flashToast("Billing settings were not updated");
      return;
    }
    await refreshBilling();
  }

  /* Text backing the active document tab. */
  const activeText = useMemo(() => {
    if (!result) return "";
    if (activeTab === "watch") return result.markdown;
    if (activeTab === "style") return result.cinematic.styleMarkdown;
    if (activeTab === "shot-specs") return result.cinematic.shotSpecMarkdown;
    if (activeTab === "prompt") return result.cinematic.promptMarkdown;
    if (activeTab === "warnings") return warningsToText(result.cinematic.slopWarnings);
    return "";
  }, [activeTab, result]);

  const renderedDoc = useMemo(
    () => (activeText ? markdownToHtml(activeText) : ""),
    [activeText]
  );

  async function copyActiveText() {
    if (!activeText) return;
    try {
      await navigator.clipboard.writeText(activeText);
      flashToast(`${TAB_LABELS[activeTab]} copied to clipboard`);
    } catch {
      flashToast("Clipboard unavailable in this browser");
    }
  }

  /* ---------------------------------------------------------------- *
   * Render                                                            *
   * ---------------------------------------------------------------- */

  const stageIndex = progress ? STAGE_PLAN.findIndex((entry) => entry.stage === progress.stage) : -1;
  const isDone = progress?.stage === "done";
  const pctLabel = Math.round((progress?.pct ?? 0) * 100);
  const runningTitle = discoveredTitle || "Reading your video";

  return (
    <main className="app">
      <div className="aurora" aria-hidden="true" />

      <SiteHeader />

      <section className="stage">
        {authLoading ? (
          <div className="auth-loading" role="status">
            <span className="auth-loading-spin" aria-hidden="true" />
            <span>Loading your account</span>
          </div>
        ) : phase === "compose" ? (
          <ComposeView
            user={user}
            billing={billing}
            onLogout={logout}
            onAuthenticated={handleAuthenticated}
            url={url}
            setUrl={setUrl}
            videoId={videoId}
            extractionKind={extractionKind}
            setExtractionKind={setExtractionKind}
            topK={topK}
            setTopK={setTopK}
            mode={mode}
            setMode={setMode}
            candidateIntervalSeconds={candidateIntervalSeconds}
            setCandidateIntervalSeconds={setCandidateIntervalSeconds}
            maxCandidateFrames={maxCandidateFrames}
            setMaxCandidateFrames={setMaxCandidateFrames}
            tuningOpen={tuningOpen}
            setTuningOpen={setTuningOpen}
            canSubmit={canSubmit}
            error={error}
            onSubmit={submit}
            saved={saved}
            savedLoading={savedLoading}
            onOpenSaved={openSavedVideo}
            onDeleteSaved={removeSavedVideo}
            onCheckout={startCheckout}
            onPortal={openBillingPortal}
            onBillingSettings={updateBillingSettings}
          />
        ) : null}

        {phase === "running" ? (
          <RunningView
            videoId={videoId}
            title={runningTitle}
            progress={progress}
            stageIndex={stageIndex}
            isDone={isDone}
            pctLabel={pctLabel}
            elapsedMs={elapsedMs}
            onCancel={cancelRun}
          />
        ) : null}

        {phase === "done" && result ? (
          <ResultView
            result={result}
            videoId={videoId}
            activeTab={activeTab}
            setActiveTab={(tab) => {
              setActiveTab(tab);
              setViewRaw(false);
            }}
            viewRaw={viewRaw}
            setViewRaw={setViewRaw}
            renderedDoc={renderedDoc}
            activeText={activeText}
            onCopy={copyActiveText}
            onReset={resetToCompose}
            openLightbox={setLightbox}
            flashToast={flashToast}
          />
        ) : null}
      </section>

      <SiteFooter />

      {lightbox !== null && result ? (
        <Lightbox
          frames={result.frames}
          index={lightbox}
          onClose={() => setLightbox(null)}
          onNavigate={(next) => setLightbox(next)}
          flashToast={flashToast}
        />
      ) : null}

      <div className={`toast ${toast ? "toast--show" : ""}`} role="status" aria-live="polite">
        {toast}
      </div>
    </main>
  );
}

/* ================================================================== *
 * Auth                                                                *
 * ================================================================== */

const AUTH_POINTS = [
  {
    title: "Frames that matter",
    body: "Vision salience and transcript density pick the representative stills — not every keyframe."
  },
  {
    title: "Cinematic grammar",
    body: "A style bible plus Blender / Remotion-ready shot specs your agents can build from."
  },
  {
    title: "Your reference archive",
    body: "Every analysis is saved to your account — reopen any past video in one click."
  }
];

const _AuthView = function AuthView(props: { onAuthenticated: (user: User) => void }) {
  const [mode, setMode] = useState<"login" | "signup">("login");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true);
    setError("");
    try {
      const response = await fetch(`/api/auth/${mode}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password })
      });
      const payload = (await response.json()) as { user?: User; error?: string };
      if (!response.ok || !payload.user) throw new Error(payload.error || "Authentication failed.");
      props.onAuthenticated(payload.user);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Authentication failed.");
    } finally {
      setBusy(false);
    }
  }

  function switchMode(next: "login" | "signup") {
    if (next === mode) return;
    setMode(next);
    setError("");
  }

  return (
    <div className="auth-shell">
      <div className="auth-copy">
        <span className="hero-eyebrow">Reference cinema → executable grammar</span>
        <h1 className="hero-title">
          Turn any YouTube video into a <em>VLM-ready context pack</em>.
        </h1>
        <p className="hero-sub">
          Timed transcript, the frames that actually matter, and the cinematic grammar underneath —
          compiled into copy-paste artifacts your coding agents can build from.
        </p>
        <ul className="auth-points">
          {AUTH_POINTS.map((point) => (
            <li key={point.title}>
              <strong>{point.title}</strong>
              <span>{point.body}</span>
            </li>
          ))}
        </ul>
      </div>

      <form className="auth-form" onSubmit={submit}>
        <p className="auth-form-kicker">
          {mode === "login" ? "Welcome back" : "Start your archive"}
        </p>

        <div className="auth-tabs" role="tablist" aria-label="Authentication mode">
          <button
            type="button"
            role="tab"
            aria-selected={mode === "login"}
            className={mode === "login" ? "is-active" : ""}
            onClick={() => switchMode("login")}
          >
            Sign in
          </button>
          <button
            type="button"
            role="tab"
            aria-selected={mode === "signup"}
            className={mode === "signup" ? "is-active" : ""}
            onClick={() => switchMode("signup")}
          >
            Create account
          </button>
        </div>

        <label className="auth-field">
          <span>Email</span>
          <input
            type="email"
            autoComplete="email"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            placeholder="you@studio.com"
            required
            autoFocus
          />
        </label>

        <label className="auth-field">
          <span>Password</span>
          <div className="auth-input-wrap">
            <input
              type={showPassword ? "text" : "password"}
              autoComplete={mode === "login" ? "current-password" : "new-password"}
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              minLength={8}
              required
            />
            <button
              type="button"
              className="auth-reveal"
              onClick={() => setShowPassword((value) => !value)}
              aria-label={showPassword ? "Hide password" : "Show password"}
            >
              {showPassword ? "Hide" : "Show"}
            </button>
          </div>
          {mode === "signup" ? (
            <span className="auth-hint">At least 8 characters</span>
          ) : null}
        </label>

        {error ? (
          <p className="error-banner" role="alert">
            {error}
          </p>
        ) : null}

        <button type="submit" className="cta" disabled={busy}>
          <span>{busy ? "Working..." : mode === "login" ? "Sign in" : "Create account"}</span>
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M5 12h14M13 5l7 7-7 7" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>

        <p className="auth-switch">
          {mode === "login" ? (
            <>
              New to yt2ctx?{" "}
              <button type="button" onClick={() => switchMode("signup")}>
                Create an account
              </button>
            </>
          ) : (
            <>
              Already have an account?{" "}
              <button type="button" onClick={() => switchMode("login")}>
                Sign in
              </button>
            </>
          )}
        </p>
      </form>
    </div>
  );
};

/* ================================================================== *
 * Compose                                                             *
 * ================================================================== */

function ComposeView(props: {
  user: User | null;
  billing: BillingSummary | null;
  onLogout: () => void;
  onAuthenticated: (user: User) => void;
  url: string;
  setUrl: (value: string) => void;
  videoId: string | null;
  extractionKind: "text" | "full";
  setExtractionKind: (value: "text" | "full") => void;
  topK: number;
  setTopK: (value: number) => void;
  mode: "density" | "top-k";
  setMode: (value: "density" | "top-k") => void;
  candidateIntervalSeconds: number;
  setCandidateIntervalSeconds: (value: number) => void;
  maxCandidateFrames: number;
  setMaxCandidateFrames: (value: number) => void;
  tuningOpen: boolean;
  setTuningOpen: (value: boolean) => void;
  canSubmit: boolean;
  error: string;
  onSubmit: () => void;
  saved: SavedVideoSummary[];
  savedLoading: boolean;
  onOpenSaved: (video: SavedVideoSummary) => void;
  onDeleteSaved: (id: string) => void;
  onCheckout: (action: "credits" | "recurring" | "setup", packId?: "starter" | "studio") => void;
  onPortal: () => void;
  onBillingSettings: (settings: { autoRefillEnabled?: boolean; recurringEnabled?: boolean }) => void;
}) {
  const hasInput = props.url.trim().length > 0;
  const showHint = hasInput && !props.videoId;
  const [failedThumbId, setFailedThumbId] = useState<string | null>(null);
  const showThumb = Boolean(props.videoId && failedThumbId !== props.videoId);

  return (
    <div className="compose">
      <div className="account-bar">
        <div>
          <span className="account-kicker">{props.user ? "Signed in" : "Guest access"}</span>
          <strong>{props.user?.email ?? "Text-only trial"}</strong>
        </div>
        {props.user ? (
          <button type="button" className="btn btn-ghost btn-sm" onClick={props.onLogout}>
            Sign out
          </button>
        ) : null}
      </div>

      <div className="compose-hero">
        <span className="hero-eyebrow">Reference cinema → executable grammar</span>
        <h1 className="hero-title">
          Turn any YouTube video into a <em>VLM-ready context pack</em>.
        </h1>
        <p className="hero-sub">
          Timed transcript, the frames that actually matter, and the cinematic grammar underneath —
          compiled into copy-paste artifacts your agents can build from.
        </p>
      </div>

      <div className="composer">
        <div className={`url-field ${props.videoId ? "url-field--valid" : ""}`}>
          <svg className="url-icon" viewBox="0 0 24 24" aria-hidden="true">
            <path
              d="M21.6 7.2a2.8 2.8 0 0 0-2-2C17.9 4.8 12 4.8 12 4.8s-5.9 0-7.6.4a2.8 2.8 0 0 0-2 2A29 29 0 0 0 2 12a29 29 0 0 0 .4 4.8 2.8 2.8 0 0 0 2 2c1.7.4 7.6.4 7.6.4s5.9 0 7.6-.4a2.8 2.8 0 0 0 2-2A29 29 0 0 0 22 12a29 29 0 0 0-.4-4.8ZM10 15V9l5.2 3-5.2 3Z"
              fill="currentColor"
            />
          </svg>
          <input
            className="url-input"
            value={props.url}
            onChange={(event) => props.setUrl(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter" && props.canSubmit) props.onSubmit();
            }}
            placeholder="Paste a YouTube link — youtube.com/watch, youtu.be, or /shorts"
            aria-label="YouTube URL"
            spellCheck={false}
            autoFocus
          />
          {props.url ? (
            <button
              type="button"
              className="url-clear"
              onClick={() => props.setUrl("")}
              aria-label="Clear URL"
            >
              ✕
            </button>
          ) : null}
        </div>

        {props.videoId && showThumb ? (
          <div className="preview">
            <img
              className="preview-thumb"
              src={thumbnailUrl(props.videoId)}
              alt="Video thumbnail"
              onError={() => setFailedThumbId(props.videoId)}
            />
            <div className="preview-body">
              <span className="preview-ok">Video detected</span>
              <span className="preview-id">ID · {props.videoId}</span>
            </div>
          </div>
        ) : null}

        {showHint ? (
          <p className="hint">That does not look like a YouTube link yet — paste a full video URL.</p>
        ) : null}

        <div className="extract-mode" role="group" aria-label="Extraction type">
          <button
            type="button"
            className={`extract-mode-btn ${props.extractionKind === "text" ? "is-active" : ""}`}
            onClick={() => props.setExtractionKind("text")}
          >
            <strong>Text only</strong>
            <span>
              {props.user
                ? `${props.billing?.free.authenticatedTextRemaining ?? 0} free left`
                : `${props.billing?.free.anonymousTextRemaining ?? 0} free left`}
            </span>
          </button>
          <button
            type="button"
            className={`extract-mode-btn ${props.extractionKind === "full" ? "is-active" : ""}`}
            onClick={() => props.user && props.setExtractionKind("full")}
            disabled={!props.user}
          >
            <strong>Full context</strong>
            <span>
              {props.user
                ? `${props.billing?.free.authenticatedFullRemaining ?? 0} free left`
                : "Sign in required"}
            </span>
          </button>
        </div>

        <button
          type="button"
          className="tuning-toggle"
          aria-expanded={props.tuningOpen}
          onClick={() => props.setTuningOpen(!props.tuningOpen)}
        >
          <span>Tuning</span>
          <span className="tuning-summary">
            {props.topK} frames · {props.mode === "density" ? "Density" : "Top K"} ·{" "}
            {props.candidateIntervalSeconds}s sampling
          </span>
          <span className={`tuning-caret ${props.tuningOpen ? "tuning-caret--open" : ""}`}>⌄</span>
        </button>

        {props.tuningOpen ? (
          <div className="tuning">
            <div className="control control--wide">
              <div className="control-head">
                <label htmlFor="topk">Frames to select</label>
                <span className="range-value">{props.topK}</span>
              </div>
              <input
                id="topk"
                className="range"
                type="range"
                min={1}
                max={24}
                value={props.topK}
                onChange={(event) => props.setTopK(Number(event.target.value))}
              />
            </div>

            <div className="control control--wide">
              <div className="control-head">
                <span>Selection mode</span>
              </div>
              <div className="seg" role="group" aria-label="Selection mode">
                <button
                  type="button"
                  className={`seg-btn ${props.mode === "density" ? "seg-btn--active" : ""}`}
                  onClick={() => props.setMode("density")}
                >
                  <strong>Density</strong>
                  <span className="seg-desc">Even coverage across the timeline</span>
                </button>
                <button
                  type="button"
                  className={`seg-btn ${props.mode === "top-k" ? "seg-btn--active" : ""}`}
                  onClick={() => props.setMode("top-k")}
                >
                  <strong>Top K</strong>
                  <span className="seg-desc">Only the highest-scoring frames</span>
                </button>
              </div>
            </div>

            <NumberControl
              id="interval"
              label="Candidate interval"
              suffix="sec"
              value={props.candidateIntervalSeconds}
              min={1}
              max={120}
              step={1}
              onChange={props.setCandidateIntervalSeconds}
            />
            <NumberControl
              id="maxcand"
              label="Max candidates"
              suffix="frames"
              value={props.maxCandidateFrames}
              min={4}
              max={80}
              step={2}
              onChange={props.setMaxCandidateFrames}
            />
          </div>
        ) : null}

        {props.error ? (
          <p className="error-banner" role="alert">
            <strong>Analysis failed.</strong> {props.error}
          </p>
        ) : null}

        <button
          type="button"
          className="cta"
          disabled={!props.canSubmit}
          onClick={props.onSubmit}
        >
          <span>Analyze video</span>
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M5 12h14M13 5l7 7-7 7" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
      </div>

      <BillingPanel
        user={props.user}
        billing={props.billing}
        onCheckout={props.onCheckout}
        onPortal={props.onPortal}
        onBillingSettings={props.onBillingSettings}
        onAuthenticated={props.onAuthenticated}
      />

      {props.user ? (
        <SavedList
          saved={props.saved}
          loading={props.savedLoading}
          onOpen={props.onOpenSaved}
          onDelete={props.onDeleteSaved}
        />
      ) : null}

      <div className="feature-row">
        <Feature title="Frames that matter" body="Vision salience, novelty, and transcript density pick the representative stills." />
        <Feature title="Cinematic grammar" body="A style bible plus Blender / Remotion-ready shot specs, not slide-deck slop." />
        <Feature title="Built for agents" body="Streaming NDJSON API, an MCP tool, and a CLI — same pipeline everywhere." />
      </div>
    </div>
  );
}

/* ================================================================== *
 * Saved videos                                                        *
 * ================================================================== */

function formatSavedAt(value: string): string {
  const date = new Date(value);
  const ms = date.getTime();
  const now = Date.now();
  const dayMs = 86_400_000;
  if (now - ms < dayMs && date.getDate() === new Date(now).getDate()) {
    return `Today · ${date.toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })}`;
  }
  if (now - ms < 2 * dayMs) {
    return `Yesterday · ${date.toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })}`;
  }
  return date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
}

function SavedList(props: {
  saved: SavedVideoSummary[];
  loading: boolean;
  onOpen: (video: SavedVideoSummary) => void;
  onDelete: (id: string) => void;
}) {
  return (
    <section className="saved" aria-label="Saved videos">
      <div className="saved-head">
        <h2 className="saved-title">Your videos</h2>
        <span className="saved-count">{props.loading ? "Syncing" : props.saved.length}</span>
      </div>
      {props.saved.length > 0 ? (
        <ul className="saved-list">
          {props.saved.map((video) => (
            <SavedRow
              key={video.id}
              video={video}
              onOpen={props.onOpen}
              onDelete={props.onDelete}
            />
          ))}
        </ul>
      ) : (
        <p className="saved-empty">
          {props.loading ? "Loading your saved videos..." : "No saved videos yet. Analyze one to start your library."}
        </p>
      )}
    </section>
  );
}

function SavedRow(props: {
  video: SavedVideoSummary;
  onOpen: (video: SavedVideoSummary) => void;
  onDelete: (id: string) => void;
}) {
  const { video } = props;
  const [thumbOk, setThumbOk] = useState(true);
  const [confirming, setConfirming] = useState(false);

  return (
    <li className="saved-row">
      <button
        type="button"
        className="saved-open"
        onClick={() => props.onOpen(video)}
      >
        {video.videoId && thumbOk ? (
          <img
            className="saved-thumb"
            src={thumbnailUrl(video.videoId)}
            alt=""
            onError={() => setThumbOk(false)}
          />
        ) : (
          <span className="saved-thumb saved-thumb--placeholder" aria-hidden="true" />
        )}
        <span className="saved-body">
          <span className="saved-name">{video.title}</span>
          <span className="saved-meta">
            {video.uploader ? `${video.uploader} · ` : ""}
            {formatTimestamp(video.durationSeconds)} · {video.frameCount} frames
          </span>
          <span className="saved-stamp">{formatSavedAt(video.createdAt)}</span>
        </span>
      </button>
      {confirming ? (
        <span className="saved-confirm">
          <button
            type="button"
            className="saved-confirm-yes"
            onClick={() => props.onDelete(video.id)}
          >
            Delete
          </button>
          <button
            type="button"
            className="saved-confirm-no"
            onClick={() => setConfirming(false)}
          >
            Keep
          </button>
        </span>
      ) : (
        <button
          type="button"
          className="saved-delete"
          onClick={() => setConfirming(true)}
          aria-label={`Delete saved video: ${video.title}`}
        >
          ✕
        </button>
      )}
    </li>
  );
}

function Feature({ title, body }: { title: string; body: string }) {
  return (
    <div className="feature">
      <h3>{title}</h3>
      <p>{body}</p>
    </div>
  );
}

function money(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

function BillingPanel(props: {
  user: User | null;
  billing: BillingSummary | null;
  onCheckout: (action: "credits" | "recurring" | "setup", packId?: "starter" | "studio") => void;
  onPortal: () => void;
  onBillingSettings: (settings: { autoRefillEnabled?: boolean; recurringEnabled?: boolean }) => void;
  onAuthenticated: (user: User) => void;
}) {
  const account = props.billing?.account;
  if (!props.user) {
    return (
      <section className="billing-panel">
        <div className="billing-copy">
          <span className="billing-kicker">Guest quota</span>
          <strong>{props.billing?.free.anonymousTextRemaining ?? 0} text-only extractions left</strong>
          <p>Sign in for 100 free text-only extractions, 10 free full context extractions, credits, and saved videos.</p>
        </div>
        <AuthMini onAuthenticated={props.onAuthenticated} />
      </section>
    );
  }

  return (
    <section className="billing-panel">
      <div className="billing-copy">
        <span className="billing-kicker">Credits</span>
        <strong>{money(account?.creditBalanceCents ?? 0)} balance</strong>
        <p>
          Free left: {props.billing?.free.authenticatedTextRemaining ?? 0} text-only ·{" "}
          {props.billing?.free.authenticatedFullRemaining ?? 0} full. Paid runs cost{" "}
          {money(props.billing?.prices.text ?? 0)} text-only or {money(props.billing?.prices.full ?? 0)} full.
        </p>
      </div>
      <div className="billing-actions">
        <button type="button" className="btn btn-primary btn-sm" onClick={() => props.onCheckout("credits", "starter")}>
          Buy $5 credits
        </button>
        <button type="button" className="btn btn-ghost btn-sm" onClick={() => props.onCheckout("credits", "studio")}>
          Buy $20 credits
        </button>
        <button type="button" className="btn btn-ghost btn-sm" onClick={() => props.onCheckout("setup")}>
          Add card
        </button>
        <button type="button" className="btn btn-ghost btn-sm" onClick={() => props.onCheckout("recurring")}>
          Monthly refill
        </button>
        <button type="button" className="btn btn-ghost btn-sm" onClick={props.onPortal}>
          Billing portal
        </button>
      </div>
      <div className="billing-toggles">
        <label>
          <input
            type="checkbox"
            checked={Boolean(account?.autoRefillEnabled)}
            onChange={(event) => props.onBillingSettings({ autoRefillEnabled: event.target.checked })}
          />
          <span>Auto-refill below {money(account?.autoRefillThresholdCents ?? 200)}</span>
        </label>
        <label>
          <input
            type="checkbox"
            checked={Boolean(account?.recurringEnabled)}
            onChange={(event) => props.onBillingSettings({ recurringEnabled: event.target.checked })}
          />
          <span>Recurring payments enabled</span>
        </label>
      </div>
    </section>
  );
}

function AuthMini(props: { onAuthenticated: (user: User) => void }) {
  const [mode, setMode] = useState<"login" | "signup">("signup");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  async function submit(event: FormEvent) {
    event.preventDefault();
    setError("");
    try {
      const response = await fetch(`/api/auth/${mode}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password })
      });
      const payload = (await response.json()) as { user?: User; error?: string };
      if (!response.ok || !payload.user) throw new Error(payload.error || "Authentication failed.");
      props.onAuthenticated(payload.user);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Authentication failed.");
    }
  }

  return (
    <form className="auth-mini" onSubmit={submit}>
      <div className="auth-mini-tabs">
        <button type="button" className={mode === "signup" ? "is-active" : ""} onClick={() => setMode("signup")}>
          Sign up
        </button>
        <button type="button" className={mode === "login" ? "is-active" : ""} onClick={() => setMode("login")}>
          Log in
        </button>
      </div>
      <input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Email" type="email" />
      <input value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Password" type="password" />
      {error ? <p className="auth-mini-error">{error}</p> : null}
      <button type="submit" className="btn btn-primary btn-sm">
        Continue
      </button>
    </form>
  );
}

function NumberControl(props: {
  id: string;
  label: string;
  suffix: string;
  value: number;
  min: number;
  max: number;
  step: number;
  onChange: (value: number) => void;
}) {
  const clamp = (next: number) => Math.min(props.max, Math.max(props.min, next));
  return (
    <div className="control">
      <div className="control-head">
        <label htmlFor={props.id}>{props.label}</label>
      </div>
      <div className="stepper">
        <button
          type="button"
          className="stepper-btn"
          onClick={() => props.onChange(clamp(props.value - props.step))}
          aria-label={`Decrease ${props.label}`}
        >
          −
        </button>
        <input
          id={props.id}
          className="stepper-input"
          type="number"
          inputMode="numeric"
          value={props.value}
          min={props.min}
          max={props.max}
          onChange={(event) => props.onChange(clamp(Number(event.target.value)))}
        />
        <span className="stepper-suffix">{props.suffix}</span>
        <button
          type="button"
          className="stepper-btn"
          onClick={() => props.onChange(clamp(props.value + props.step))}
          aria-label={`Increase ${props.label}`}
        >
          +
        </button>
      </div>
    </div>
  );
}

/* ================================================================== *
 * Running                                                             *
 * ================================================================== */

function RunningView(props: {
  videoId: string | null;
  title: string;
  progress: ProgressEvent | null;
  stageIndex: number;
  isDone: boolean;
  pctLabel: number;
  elapsedMs: number;
  onCancel: () => void;
}) {
  const [thumbOk, setThumbOk] = useState(true);
  const detail = props.progress?.detail;
  const showDetailInHeader =
    detail && props.progress?.stage !== "download"; // download detail is the title

  return (
    <div className="running">
      <div className="run-screen">
        {props.videoId && thumbOk ? (
          <img
            className="run-thumb"
            src={thumbnailUrl(props.videoId)}
            alt=""
            onError={() => setThumbOk(false)}
          />
        ) : (
          <div className="run-thumb run-thumb--placeholder" />
        )}
        <div className="run-vignette" aria-hidden="true" />
        <div className="scanline" aria-hidden="true" />
        <div className="run-screen-label">
          <span className="run-eyebrow">Analyzing</span>
          <span className="run-title">{props.title}</span>
        </div>
      </div>

      <div className="run-meta">
        <div className="run-headline">
          <span className="run-pct">{props.pctLabel}%</span>
          <div className="run-headline-text">
            <strong>{props.progress?.label ?? "Starting"}</strong>
            <span>{showDetailInHeader ? detail : "Hold tight — this usually takes 1–4 minutes."}</span>
          </div>
          <span className="run-clock" aria-label="Elapsed time">
            {formatClock(props.elapsedMs)}
          </span>
        </div>

        <div className="run-bar" role="progressbar" aria-valuenow={props.pctLabel} aria-valuemin={0} aria-valuemax={100}>
          <div className="run-bar-fill" style={{ width: `${Math.max(2, props.pctLabel)}%` }} />
        </div>
      </div>

      <ol className="pipeline">
        {STAGE_PLAN.map((entry, index) => {
          const status = props.isDone || index < props.stageIndex
            ? "done"
            : index === props.stageIndex
              ? "active"
              : "pending";
          const showSub =
            status === "active" &&
            props.progress?.total != null &&
            props.progress.total > 1 &&
            props.progress.current != null;
          const subPct = showSub
            ? Math.round(((props.progress!.current ?? 0) / props.progress!.total!) * 100)
            : 0;
          return (
            <li key={entry.stage} className={`step step--${status}`}>
              <span className="step-icon" aria-hidden="true">
                {status === "done" ? "✓" : status === "active" ? <span className="step-spin" /> : index + 1}
              </span>
              <div className="step-body">
                <span className="step-label">{entry.label}</span>
                <span className="step-detail">
                  {status === "active" && props.progress?.detail
                    ? props.progress.detail
                    : entry.blurb}
                </span>
                {showSub ? (
                  <div className="step-bar">
                    <div className="step-bar-fill" style={{ width: `${Math.max(4, subPct)}%` }} />
                  </div>
                ) : null}
              </div>
              {showSub ? (
                <span className="step-count">
                  {props.progress!.current}/{props.progress!.total}
                </span>
              ) : null}
            </li>
          );
        })}
      </ol>

      <button type="button" className="cancel" onClick={props.onCancel}>
        Cancel analysis
      </button>
    </div>
  );
}

/* ================================================================== *
 * Result                                                              *
 * ================================================================== */

function ResultView(props: {
  result: AnalyzeResult;
  videoId: string | null;
  activeTab: ResultTab;
  setActiveTab: (tab: ResultTab) => void;
  viewRaw: boolean;
  setViewRaw: (value: boolean) => void;
  renderedDoc: string;
  activeText: string;
  onCopy: () => void;
  onReset: () => void;
  openLightbox: (index: number) => void;
  flashToast: (message: string) => void;
}) {
  const { result } = props;
  const [thumbOk, setThumbOk] = useState(true);
  const shotCount = result.cinematic.shotSpecs?.length ?? 0;
  const warnCount = result.cinematic.slopWarnings.length;

  const tabs: ResultTab[] = ["watch", "frames", "style", "shot-specs", "prompt", "warnings"];
  const counts: Partial<Record<ResultTab, number>> = {
    frames: result.frames.length,
    "shot-specs": shotCount,
    warnings: warnCount
  };

  const tabFile = TAB_FILES[props.activeTab];

  return (
    <div className="result">
      <div className="result-hero">
        {props.videoId && thumbOk ? (
          <img
            className="result-thumb"
            src={thumbnailUrl(props.videoId)}
            alt=""
            onError={() => setThumbOk(false)}
          />
        ) : (
          <div className="result-thumb result-thumb--placeholder" />
        )}
        <div className="result-headings">
          <span className="result-eyebrow">Context pack ready</span>
          <h1 className="result-title">{result.metadata.title || "Analyzed video"}</h1>
          <p className="result-meta">
            {result.metadata.uploader ? `${result.metadata.uploader} · ` : ""}
            {formatTimestamp(result.metadata.durationSeconds)} runtime
          </p>
          <div className="chips">
            <span className="chip">{result.frames.length} frames</span>
            <span className="chip">{shotCount} shot specs</span>
            <span className="chip">{warnCount} slop guards</span>
            <span className="chip chip--muted">{result.options.visionModel}</span>
          </div>
        </div>
        <div className="result-actions">
          <button
            type="button"
            className="btn btn-primary"
            onClick={() => {
              downloadBlob(result.zipDownloadUrl, `${result.id}.zip`);
              props.flashToast("Artifact ZIP downloading");
            }}
          >
            Download ZIP
          </button>
          <button type="button" className="btn btn-ghost" onClick={props.onReset}>
            New analysis
          </button>
        </div>
      </div>

      <div className="tabs" role="tablist" aria-label="Result sections">
        {tabs.map((tab) => (
          <button
            key={tab}
            role="tab"
            aria-selected={props.activeTab === tab}
            className={`tab ${props.activeTab === tab ? "tab--active" : ""}`}
            onClick={() => props.setActiveTab(tab)}
          >
            {TAB_LABELS[tab]}
            {counts[tab] != null ? <span className="tab-badge">{counts[tab]}</span> : null}
          </button>
        ))}
      </div>

      <div className="panel">
        {props.activeTab === "frames" ? (
          <FramesGrid frames={result.frames} onOpen={props.openLightbox} flashToast={props.flashToast} />
        ) : props.activeTab === "warnings" ? (
          <WarningsList warnings={result.cinematic.slopWarnings} onCopy={props.onCopy} />
        ) : (
          <div className="doc-wrap">
            <div className="doc-toolbar">
              <div className="doc-view-toggle" role="group" aria-label="Document view">
                <button
                  type="button"
                  className={!props.viewRaw ? "is-active" : ""}
                  onClick={() => props.setViewRaw(false)}
                >
                  Reading
                </button>
                <button
                  type="button"
                  className={props.viewRaw ? "is-active" : ""}
                  onClick={() => props.setViewRaw(true)}
                >
                  Raw
                </button>
              </div>
              <div className="doc-toolbar-actions">
                <button type="button" className="btn btn-ghost btn-sm" onClick={props.onCopy}>
                  Copy
                </button>
                {tabFile ? (
                  <button
                    type="button"
                    className="btn btn-ghost btn-sm"
                    onClick={() => {
                      downloadText(props.activeText, tabFile);
                      props.flashToast(`${tabFile} downloading`);
                    }}
                  >
                    Download .md
                  </button>
                ) : null}
              </div>
            </div>
            {props.viewRaw ? (
              <pre className="doc-raw">{props.activeText}</pre>
            ) : (
              <article
                className="doc"
                dangerouslySetInnerHTML={{ __html: props.renderedDoc }}
              />
            )}
          </div>
        )}
      </div>
    </div>
  );
}

function FramesGrid(props: {
  frames: Frame[];
  onOpen: (index: number) => void;
  flashToast: (message: string) => void;
}) {
  return (
    <div className="frames-grid">
      {props.frames.map((frame, index) => (
        <article className="frame-card" key={frame.fileName}>
          <button
            type="button"
            className="frame-img-btn"
            onClick={() => props.onOpen(index)}
            aria-label={`Open frame at ${formatTimestamp(frame.timestamp)}`}
          >
            <img className="frame-img" src={frame.imageUrl} alt={frame.description} loading="lazy" />
            <span className="frame-time">{formatTimestamp(frame.timestamp)}</span>
            <span className="frame-expand" aria-hidden="true">⤢</span>
          </button>
          <div className="frame-info">
            <div className="frame-score">
              <span className="frame-score-label">salience</span>
              <span className="score-meter">
                <span
                  className="score-meter-fill"
                  style={{ width: `${Math.min(100, Math.round(frame.score * 100))}%` }}
                />
              </span>
              <span className="frame-score-num">{frame.score.toFixed(2)}</span>
            </div>
            <p className="frame-desc">{frame.description}</p>
            <div className="tag-row">
              {frame.labels.slice(0, 6).map((label) => (
                <span className="tag" key={label}>
                  {label}
                </span>
              ))}
            </div>
            <button
              type="button"
              className="btn btn-ghost btn-sm frame-dl"
              onClick={() => {
                downloadBlob(frame.imageDownloadUrl, frame.fileName);
                props.flashToast("Frame downloading");
              }}
            >
              Download frame
            </button>
          </div>
        </article>
      ))}
    </div>
  );
}

function WarningsList(props: { warnings: SlopWarning[]; onCopy: () => void }) {
  if (props.warnings.length === 0) {
    return <p className="empty-note">No slop warnings were generated for this reference.</p>;
  }
  return (
    <div className="warn-wrap">
      <div className="doc-toolbar">
        <p className="warn-intro">Validator-ready rules — reject generated shots that trip these.</p>
        <button type="button" className="btn btn-ghost btn-sm" onClick={props.onCopy}>
          Copy all
        </button>
      </div>
      <div className="warn-list">
        {props.warnings.map((warning) => (
          <article className="warn-card" key={warning.rule}>
            <h3 className="warn-rule">{warning.rule}</h3>
            <p className="warn-why">{warning.whyItBreaksTaste}</p>
            <dl className="warn-dl">
              <dt>Reject if</dt>
              <dd>{warning.rejectIf}</dd>
              <dt>Prefer</dt>
              <dd>{warning.preferredMove}</dd>
            </dl>
          </article>
        ))}
      </div>
    </div>
  );
}

/* ================================================================== *
 * Lightbox                                                            *
 * ================================================================== */

function Lightbox(props: {
  frames: Frame[];
  index: number;
  onClose: () => void;
  onNavigate: (next: number) => void;
  flashToast: (message: string) => void;
}) {
  const frame = props.frames[props.index];
  if (!frame) return null;
  const go = (delta: number) =>
    props.onNavigate((props.index + delta + props.frames.length) % props.frames.length);

  return (
    <div className="lightbox" role="dialog" aria-modal="true" onClick={props.onClose}>
      <button className="lightbox-close" type="button" onClick={props.onClose} aria-label="Close">
        ✕
      </button>
      <button
        className="lightbox-nav lightbox-nav--prev"
        type="button"
        onClick={(event) => {
          event.stopPropagation();
          go(-1);
        }}
        aria-label="Previous frame"
      >
        ‹
      </button>
      <div className="lightbox-inner" onClick={(event) => event.stopPropagation()}>
        <img className="lightbox-img" src={frame.imageUrl} alt={frame.description} />
        <div className="lightbox-side">
          <div className="lightbox-head">
            <span className="lightbox-time">{formatTimestamp(frame.timestamp)}</span>
            <span className="lightbox-index">
              {props.index + 1} / {props.frames.length}
            </span>
          </div>
          <p className="lightbox-desc">{frame.description}</p>
          <div className="tag-row">
            {frame.labels.map((label) => (
              <span className="tag" key={label}>
                {label}
              </span>
            ))}
          </div>
          {frame.transcriptContext ? (
            <div className="lightbox-transcript">
              <span className="lightbox-field-label">Nearby transcript</span>
              <p>{frame.transcriptContext}</p>
            </div>
          ) : null}
          <div className="lightbox-score">
            <span className="lightbox-field-label">Salience score</span>
            <span className="score-meter">
              <span
                className="score-meter-fill"
                style={{ width: `${Math.min(100, Math.round(frame.score * 100))}%` }}
              />
            </span>
            <span>{frame.score.toFixed(3)}</span>
          </div>
          <button
            type="button"
            className="btn btn-primary btn-sm"
            onClick={() => {
              downloadBlob(frame.imageDownloadUrl, frame.fileName);
              props.flashToast("Frame downloading");
            }}
          >
            Download frame
          </button>
        </div>
      </div>
      <button
        className="lightbox-nav lightbox-nav--next"
        type="button"
        onClick={(event) => {
          event.stopPropagation();
          go(1);
        }}
        aria-label="Next frame"
      >
        ›
      </button>
    </div>
  );
}
